#!/bin/bash
gcc adsb_G1.c -o adsb_G1 -g -Wall
./adsb_G1 ./data/MODEL1/data0 ./data/MODEL1/range0 ./data/MODEL1/myans0
./adsb_G1 ./data/MODEL1/data1 ./data/MODEL1/range1 ./data/MODEL1/myans1
./adsb_G1 ./data/MODEL1/data2 ./data/MODEL1/range2 ./data/MODEL1/myans2
./adsb_G1 ./data/MODEL1/data3 ./data/MODEL1/range3 ./data/MODEL1/myans3
./adsb_G1 ./data/MODEL1/data4 ./data/MODEL1/range4 ./data/MODEL1/myans4
./adsb_G1 ./data/MODEL1/data5 ./data/MODEL1/range5 ./data/MODEL1/myans5
./adsb_G1 ./data/MODEL1/data6 ./data/MODEL1/range6 ./data/MODEL1/myans6
./adsb_G1 ./data/MODEL1/data7 ./data/MODEL1/range7 ./data/MODEL1/myans7
./adsb_G1 ./data/MODEL1/data8 ./data/MODEL1/range8 ./data/MODEL1/myans8
./adsb_G1 ./data/MODEL1/data9 ./data/MODEL1/range9 ./data/MODEL1/myans9
./adsb_G1 ./data/MODEL2/data0 ./data/MODEL2/range0 ./data/MODEL2/myans0
./adsb_G1 ./data/MODEL2/data1 ./data/MODEL2/range1 ./data/MODEL2/myans1
./adsb_G1 ./data/MODEL2/data2 ./data/MODEL2/range2 ./data/MODEL2/myans2
./adsb_G1 ./data/MODEL2/data3 ./data/MODEL2/range3 ./data/MODEL2/myans3
./adsb_G1 ./data/MODEL2/data4 ./data/MODEL2/range4 ./data/MODEL2/myans4
./adsb_G1 ./data/MODEL2/data5 ./data/MODEL2/range5 ./data/MODEL2/myans5
./adsb_G1 ./data/MODEL2/data6 ./data/MODEL2/range6 ./data/MODEL2/myans6
./adsb_G1 ./data/MODEL2/data7 ./data/MODEL2/range7 ./data/MODEL2/myans7
./adsb_G1 ./data/MODEL2/data8 ./data/MODEL2/range8 ./data/MODEL2/myans8
./adsb_G1 ./data/MODEL2/data9 ./data/MODEL2/range9 ./data/MODEL2/myans9
