#!/bin/bash
gcc adsb_G1.c -o adsb_G1 -g -Wall
./adsb_G1 ./data/MODEL1_rev/data0 ./data/MODEL1_rev/range0 ./data/MODEL1_rev/myans0
./adsb_G1 ./data/MODEL1_rev/data1 ./data/MODEL1_rev/range1 ./data/MODEL1_rev/myans1
./adsb_G1 ./data/MODEL1_rev/data2 ./data/MODEL1_rev/range2 ./data/MODEL1_rev/myans2
./adsb_G1 ./data/MODEL1_rev/data3 ./data/MODEL1_rev/range3 ./data/MODEL1_rev/myans3
./adsb_G1 ./data/MODEL1_rev/data4 ./data/MODEL1_rev/range4 ./data/MODEL1_rev/myans4
./adsb_G1 ./data/MODEL1_rev/data5 ./data/MODEL1_rev/range5 ./data/MODEL1_rev/myans5
./adsb_G1 ./data/MODEL1_rev/data6 ./data/MODEL1_rev/range6 ./data/MODEL1_rev/myans6
./adsb_G1 ./data/MODEL1_rev/data7 ./data/MODEL1_rev/range7 ./data/MODEL1_rev/myans7
./adsb_G1 ./data/MODEL1_rev/data8 ./data/MODEL1_rev/range8 ./data/MODEL1_rev/myans8
./adsb_G1 ./data/MODEL1_rev/data9 ./data/MODEL1_rev/range9 ./data/MODEL1_rev/myans9
./adsb_G1 ./data/MODEL2_rev/data0 ./data/MODEL2_rev/range0 ./data/MODEL2_rev/myans0
./adsb_G1 ./data/MODEL2_rev/data1 ./data/MODEL2_rev/range1 ./data/MODEL2_rev/myans1
./adsb_G1 ./data/MODEL2_rev/data2 ./data/MODEL2_rev/range2 ./data/MODEL2_rev/myans2
./adsb_G1 ./data/MODEL2_rev/data3 ./data/MODEL2_rev/range3 ./data/MODEL2_rev/myans3
./adsb_G1 ./data/MODEL2_rev/data4 ./data/MODEL2_rev/range4 ./data/MODEL2_rev/myans4
./adsb_G1 ./data/MODEL2_rev/data5 ./data/MODEL2_rev/range5 ./data/MODEL2_rev/myans5
./adsb_G1 ./data/MODEL2_rev/data6 ./data/MODEL2_rev/range6 ./data/MODEL2_rev/myans6
./adsb_G1 ./data/MODEL2_rev/data7 ./data/MODEL2_rev/range7 ./data/MODEL2_rev/myans7
./adsb_G1 ./data/MODEL2_rev/data8 ./data/MODEL2_rev/range8 ./data/MODEL2_rev/myans8
./adsb_G1 ./data/MODEL2_rev/data9 ./data/MODEL2_rev/range9 ./data/MODEL2_rev/myans9
